#include <climits>

#ifndef IDDS_XML_TYPES_H
#define IDDS_XML_TYPES_H

#define ERR_CONV_DEFAULT INT_MAX
#define MAX_ALLOWED_REQUEST_ROOT_CHILDREN 2
#define MAX_ALLOWED_RESPONSE_ROOT_CHILDREN 3

#endif // IDDS_XML_TYPES_H
